/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AddOrUpdateResult = IDL.Variant({
  'updateError' : IDL.Null,
  'duplicateError' : IDL.Null,
  'success' : IDL.Null,
  'notFoundError' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const FixReviewStatusResult = IDL.Variant({
  'invalidProposal' : IDL.Null,
  'invalidReviewer' : IDL.Null,
  'alreadyCorrect' : IDL.Null,
  'fixedReviewStatus' : IDL.Null,
});
export const ReviewerAssignment = IDL.Record({
  'endDate' : IDL.Int,
  'startDate' : IDL.Int,
});
export const Reviewer = IDL.Record({
  'principal' : IDL.Principal,
  'nickname' : IDL.Text,
  'forumProfileUrl' : IDL.Text,
});
export const ReviewerWithAssignments = IDL.Record({
  'assignments' : IDL.Vec(IDL.Tuple(IDL.Nat, ReviewerAssignment)),
  'reviewer' : Reviewer,
});
export const UserProfile = IDL.Record({
  'nickname' : IDL.Text,
  'forumProfileUrl' : IDL.Text,
});
export const Proposal = IDL.Record({
  'title' : IDL.Text,
  'topic' : IDL.Nat,
  'deadlineDate' : IDL.Int,
  'deadline' : IDL.Int,
  'creationDate' : IDL.Int,
  'timestamp' : IDL.Int,
  'proposalId' : IDL.Nat,
});
export const Recommendation = IDL.Variant({
  'reject' : IDL.Null,
  'adopt' : IDL.Null,
});
export const Review = IDL.Record({
  'status' : IDL.Variant({ 'paid' : IDL.Null, 'volunteer' : IDL.Null }),
  'topic' : IDL.Nat,
  'link' : IDL.Text,
  'timestamp' : IDL.Int,
  'recommendation' : Recommendation,
  'reviewer' : Reviewer,
  'proposalId' : IDL.Nat,
});
export const ReviewerStatus = IDL.Variant({
  'paidGrantee' : IDL.Null,
  'volunteerFormerGrantee' : IDL.Null,
  'volunteer' : IDL.Null,
});
export const ReviewerDetail = IDL.Record({
  'paidReviews' : IDL.Nat,
  'status' : ReviewerStatus,
  'currentAssignments' : IDL.Vec(IDL.Tuple(IDL.Nat, ReviewerAssignment)),
  'totalReviews' : IDL.Nat,
  'reviewer' : Reviewer,
  'voluntaryReviews' : IDL.Nat,
  'allAssignments' : IDL.Vec(IDL.Tuple(IDL.Nat, ReviewerAssignment)),
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAdmin' : IDL.Func([IDL.Principal], [], []),
  'addOrUpdateReviewer' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Text],
      [AddOrUpdateResult],
      [],
    ),
  'addProposal' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Int, IDL.Int, IDL.Int, IDL.Int, IDL.Nat],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignReviewerToTopic' : IDL.Func(
      [IDL.Principal, IDL.Nat, IDL.Int, IDL.Int],
      [],
      [],
    ),
  'clearAllProposals' : IDL.Func([], [], []),
  'fetchIndividualProposal' : IDL.Func([IDL.Nat], [IDL.Text], []),
  'fixReviewStatus' : IDL.Func(
      [IDL.Nat, IDL.Principal],
      [FixReviewStatusResult],
      [],
    ),
  'getAllAdmins' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getAllProposalIds' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
  'getAllReviewers' : IDL.Func(
      [],
      [IDL.Vec(ReviewerWithAssignments)],
      ['query'],
    ),
  'getAllTopics' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text))],
      ['query'],
    ),
  'getAuthorizedProposalSubmitter' : IDL.Func(
      [],
      [IDL.Opt(IDL.Principal)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getProposal' : IDL.Func([IDL.Nat], [IDL.Opt(Proposal)], ['query']),
  'getProposalReviews' : IDL.Func([IDL.Nat], [IDL.Vec(Review)], ['query']),
  'getProposals' : IDL.Func([IDL.Opt(IDL.Nat)], [IDL.Vec(Proposal)], ['query']),
  'getRecommendationCounts' : IDL.Func(
      [IDL.Nat],
      [IDL.Nat, IDL.Nat],
      ['query'],
    ),
  'getReviewer' : IDL.Func([IDL.Principal], [IDL.Opt(Reviewer)], ['query']),
  'getReviewerAssignments' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Tuple(IDL.Nat, ReviewerAssignment))],
      ['query'],
    ),
  'getReviewerDetail' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(ReviewerDetail)],
      ['query'],
    ),
  'getReviewerMissedProposals' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Proposal)],
      ['query'],
    ),
  'getReviewerReviewHistory' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Review)],
      ['query'],
    ),
  'getReviewerTodos' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Proposal)],
      ['query'],
    ),
  'getTopicDisplayName' : IDL.Func([IDL.Nat], [IDL.Text], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isAdmin' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isReviewer' : IDL.Func([], [IDL.Bool], ['query']),
  'removeAdmin' : IDL.Func([IDL.Principal], [], []),
  'removeProposal' : IDL.Func([IDL.Nat], [], []),
  'removeReviewer' : IDL.Func([IDL.Principal], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveExternalProposal' : IDL.Func([Proposal], [IDL.Bool], []),
  'saveExternalProposals' : IDL.Func(
      [IDL.Vec(Proposal)],
      [IDL.Vec(IDL.Nat)],
      [],
    ),
  'setAuthorizedProposalSubmitter' : IDL.Func([IDL.Opt(IDL.Principal)], [], []),
  'submitReview' : IDL.Func([IDL.Nat, IDL.Text, Recommendation], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateReviewLink' : IDL.Func(
      [IDL.Nat, IDL.Principal, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'updateReviewer' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Text],
      [AddOrUpdateResult],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AddOrUpdateResult = IDL.Variant({
    'updateError' : IDL.Null,
    'duplicateError' : IDL.Null,
    'success' : IDL.Null,
    'notFoundError' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const FixReviewStatusResult = IDL.Variant({
    'invalidProposal' : IDL.Null,
    'invalidReviewer' : IDL.Null,
    'alreadyCorrect' : IDL.Null,
    'fixedReviewStatus' : IDL.Null,
  });
  const ReviewerAssignment = IDL.Record({
    'endDate' : IDL.Int,
    'startDate' : IDL.Int,
  });
  const Reviewer = IDL.Record({
    'principal' : IDL.Principal,
    'nickname' : IDL.Text,
    'forumProfileUrl' : IDL.Text,
  });
  const ReviewerWithAssignments = IDL.Record({
    'assignments' : IDL.Vec(IDL.Tuple(IDL.Nat, ReviewerAssignment)),
    'reviewer' : Reviewer,
  });
  const UserProfile = IDL.Record({
    'nickname' : IDL.Text,
    'forumProfileUrl' : IDL.Text,
  });
  const Proposal = IDL.Record({
    'title' : IDL.Text,
    'topic' : IDL.Nat,
    'deadlineDate' : IDL.Int,
    'deadline' : IDL.Int,
    'creationDate' : IDL.Int,
    'timestamp' : IDL.Int,
    'proposalId' : IDL.Nat,
  });
  const Recommendation = IDL.Variant({
    'reject' : IDL.Null,
    'adopt' : IDL.Null,
  });
  const Review = IDL.Record({
    'status' : IDL.Variant({ 'paid' : IDL.Null, 'volunteer' : IDL.Null }),
    'topic' : IDL.Nat,
    'link' : IDL.Text,
    'timestamp' : IDL.Int,
    'recommendation' : Recommendation,
    'reviewer' : Reviewer,
    'proposalId' : IDL.Nat,
  });
  const ReviewerStatus = IDL.Variant({
    'paidGrantee' : IDL.Null,
    'volunteerFormerGrantee' : IDL.Null,
    'volunteer' : IDL.Null,
  });
  const ReviewerDetail = IDL.Record({
    'paidReviews' : IDL.Nat,
    'status' : ReviewerStatus,
    'currentAssignments' : IDL.Vec(IDL.Tuple(IDL.Nat, ReviewerAssignment)),
    'totalReviews' : IDL.Nat,
    'reviewer' : Reviewer,
    'voluntaryReviews' : IDL.Nat,
    'allAssignments' : IDL.Vec(IDL.Tuple(IDL.Nat, ReviewerAssignment)),
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAdmin' : IDL.Func([IDL.Principal], [], []),
    'addOrUpdateReviewer' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Text],
        [AddOrUpdateResult],
        [],
      ),
    'addProposal' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Int, IDL.Int, IDL.Int, IDL.Int, IDL.Nat],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignReviewerToTopic' : IDL.Func(
        [IDL.Principal, IDL.Nat, IDL.Int, IDL.Int],
        [],
        [],
      ),
    'clearAllProposals' : IDL.Func([], [], []),
    'fetchIndividualProposal' : IDL.Func([IDL.Nat], [IDL.Text], []),
    'fixReviewStatus' : IDL.Func(
        [IDL.Nat, IDL.Principal],
        [FixReviewStatusResult],
        [],
      ),
    'getAllAdmins' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getAllProposalIds' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
    'getAllReviewers' : IDL.Func(
        [],
        [IDL.Vec(ReviewerWithAssignments)],
        ['query'],
      ),
    'getAllTopics' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text))],
        ['query'],
      ),
    'getAuthorizedProposalSubmitter' : IDL.Func(
        [],
        [IDL.Opt(IDL.Principal)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getProposal' : IDL.Func([IDL.Nat], [IDL.Opt(Proposal)], ['query']),
    'getProposalReviews' : IDL.Func([IDL.Nat], [IDL.Vec(Review)], ['query']),
    'getProposals' : IDL.Func(
        [IDL.Opt(IDL.Nat)],
        [IDL.Vec(Proposal)],
        ['query'],
      ),
    'getRecommendationCounts' : IDL.Func(
        [IDL.Nat],
        [IDL.Nat, IDL.Nat],
        ['query'],
      ),
    'getReviewer' : IDL.Func([IDL.Principal], [IDL.Opt(Reviewer)], ['query']),
    'getReviewerAssignments' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Tuple(IDL.Nat, ReviewerAssignment))],
        ['query'],
      ),
    'getReviewerDetail' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(ReviewerDetail)],
        ['query'],
      ),
    'getReviewerMissedProposals' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Proposal)],
        ['query'],
      ),
    'getReviewerReviewHistory' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Review)],
        ['query'],
      ),
    'getReviewerTodos' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Proposal)],
        ['query'],
      ),
    'getTopicDisplayName' : IDL.Func([IDL.Nat], [IDL.Text], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isAdmin' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isReviewer' : IDL.Func([], [IDL.Bool], ['query']),
    'removeAdmin' : IDL.Func([IDL.Principal], [], []),
    'removeProposal' : IDL.Func([IDL.Nat], [], []),
    'removeReviewer' : IDL.Func([IDL.Principal], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveExternalProposal' : IDL.Func([Proposal], [IDL.Bool], []),
    'saveExternalProposals' : IDL.Func(
        [IDL.Vec(Proposal)],
        [IDL.Vec(IDL.Nat)],
        [],
      ),
    'setAuthorizedProposalSubmitter' : IDL.Func(
        [IDL.Opt(IDL.Principal)],
        [],
        [],
      ),
    'submitReview' : IDL.Func([IDL.Nat, IDL.Text, Recommendation], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateReviewLink' : IDL.Func(
        [IDL.Nat, IDL.Principal, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'updateReviewer' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Text],
        [AddOrUpdateResult],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };