/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AddOrUpdateResult = { 'updateError' : null } |
  { 'duplicateError' : null } |
  { 'success' : null } |
  { 'notFoundError' : null };
export type FixReviewStatusResult = { 'invalidProposal' : null } |
  { 'invalidReviewer' : null } |
  { 'alreadyCorrect' : null } |
  { 'fixedReviewStatus' : null };
export interface Proposal {
  'title' : string,
  'topic' : bigint,
  'deadlineDate' : bigint,
  'deadline' : bigint,
  'creationDate' : bigint,
  'timestamp' : bigint,
  'proposalId' : bigint,
}
export type Recommendation = { 'reject' : null } |
  { 'adopt' : null };
export interface Review {
  'status' : { 'paid' : null } |
    { 'volunteer' : null },
  'topic' : bigint,
  'link' : string,
  'timestamp' : bigint,
  'recommendation' : Recommendation,
  'reviewer' : Reviewer,
  'proposalId' : bigint,
}
export interface Reviewer {
  'principal' : Principal,
  'nickname' : string,
  'forumProfileUrl' : string,
}
export interface ReviewerAssignment { 'endDate' : bigint, 'startDate' : bigint }
export interface ReviewerDetail {
  'paidReviews' : bigint,
  'status' : ReviewerStatus,
  'currentAssignments' : Array<[bigint, ReviewerAssignment]>,
  'totalReviews' : bigint,
  'reviewer' : Reviewer,
  'voluntaryReviews' : bigint,
  'allAssignments' : Array<[bigint, ReviewerAssignment]>,
}
export type ReviewerStatus = { 'paidGrantee' : null } |
  { 'volunteerFormerGrantee' : null } |
  { 'volunteer' : null };
export interface ReviewerWithAssignments {
  'assignments' : Array<[bigint, ReviewerAssignment]>,
  'reviewer' : Reviewer,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'nickname' : string, 'forumProfileUrl' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAdmin' : ActorMethod<[Principal], undefined>,
  'addOrUpdateReviewer' : ActorMethod<
    [Principal, string, string],
    AddOrUpdateResult
  >,
  'addProposal' : ActorMethod<
    [bigint, string, bigint, bigint, bigint, bigint, bigint],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignReviewerToTopic' : ActorMethod<
    [Principal, bigint, bigint, bigint],
    undefined
  >,
  'clearAllProposals' : ActorMethod<[], undefined>,
  'fetchIndividualProposal' : ActorMethod<[bigint], string>,
  'fixReviewStatus' : ActorMethod<[bigint, Principal], FixReviewStatusResult>,
  'getAllAdmins' : ActorMethod<[], Array<Principal>>,
  'getAllProposalIds' : ActorMethod<[], Array<bigint>>,
  'getAllReviewers' : ActorMethod<[], Array<ReviewerWithAssignments>>,
  'getAllTopics' : ActorMethod<[], Array<[bigint, string]>>,
  'getAuthorizedProposalSubmitter' : ActorMethod<[], [] | [Principal]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getProposal' : ActorMethod<[bigint], [] | [Proposal]>,
  'getProposalReviews' : ActorMethod<[bigint], Array<Review>>,
  'getProposals' : ActorMethod<[[] | [bigint]], Array<Proposal>>,
  'getRecommendationCounts' : ActorMethod<[bigint], [bigint, bigint]>,
  'getReviewer' : ActorMethod<[Principal], [] | [Reviewer]>,
  'getReviewerAssignments' : ActorMethod<
    [Principal],
    Array<[bigint, ReviewerAssignment]>
  >,
  'getReviewerDetail' : ActorMethod<[Principal], [] | [ReviewerDetail]>,
  'getReviewerMissedProposals' : ActorMethod<[Principal], Array<Proposal>>,
  'getReviewerReviewHistory' : ActorMethod<[Principal], Array<Review>>,
  'getReviewerTodos' : ActorMethod<[Principal], Array<Proposal>>,
  'getTopicDisplayName' : ActorMethod<[bigint], string>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isAdmin' : ActorMethod<[Principal], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isReviewer' : ActorMethod<[], boolean>,
  'removeAdmin' : ActorMethod<[Principal], undefined>,
  'removeProposal' : ActorMethod<[bigint], undefined>,
  'removeReviewer' : ActorMethod<[Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveExternalProposal' : ActorMethod<[Proposal], boolean>,
  'saveExternalProposals' : ActorMethod<[Array<Proposal>], Array<bigint>>,
  'setAuthorizedProposalSubmitter' : ActorMethod<[[] | [Principal]], undefined>,
  'submitReview' : ActorMethod<[bigint, string, Recommendation], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateReviewLink' : ActorMethod<[bigint, Principal, string], boolean>,
  'updateReviewer' : ActorMethod<
    [Principal, string, string],
    AddOrUpdateResult
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];