/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
import type { AuditLogEntry, AuditActionType } from "./lib/auditTypes";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface Reviewer {
    principal: Principal;
    nickname: string;
    forumProfileUrl: string;
}
export interface ReviewerWithAssignments {
    assignments: Array<[bigint, ReviewerAssignment]>;
    reviewer: Reviewer;
}
export interface Proposal {
    title: string;
    topic: bigint;
    deadlineDate: bigint;
    deadline: bigint;
    creationDate: bigint;
    timestamp: bigint;
    proposalId: bigint;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface ReviewerDetail {
    paidReviews: bigint;
    status: ReviewerStatus;
    currentAssignments: Array<[bigint, ReviewerAssignment]>;
    totalReviews: bigint;
    reviewer: Reviewer;
    voluntaryReviews: bigint;
    allAssignments: Array<[bigint, ReviewerAssignment]>;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface ReviewerAssignment {
    endDate: bigint;
    startDate: bigint;
}
export interface Review {
    status: Variant_paid_volunteer;
    topic: bigint;
    link: string;
    timestamp: bigint;
    recommendation: Recommendation;
    reviewer: Reviewer;
    proposalId: bigint;
}
export interface UserProfile {
    nickname: string;
    forumProfileUrl: string;
}
export enum AddOrUpdateResult {
    updateError = "updateError",
    duplicateError = "duplicateError",
    success = "success",
    notFoundError = "notFoundError"
}
export enum FixReviewStatusResult {
    invalidProposal = "invalidProposal",
    invalidReviewer = "invalidReviewer",
    alreadyCorrect = "alreadyCorrect",
    fixedReviewStatus = "fixedReviewStatus"
}
export enum Recommendation {
    reject = "reject",
    adopt = "adopt"
}
export enum ReviewerStatus {
    paidGrantee = "paidGrantee",
    volunteerFormerGrantee = "volunteerFormerGrantee",
    volunteer = "volunteer"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_paid_volunteer {
    paid = "paid",
    volunteer = "volunteer"
}

export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addAdmin(principal: Principal): Promise<void>;
    addOrUpdateReviewer(principal: Principal, nickname: string, forumProfileUrl: string): Promise<AddOrUpdateResult>;
    addProposal(proposalId: bigint, title: string, timestamp: bigint, deadline: bigint, creationDate: bigint, deadlineDate: bigint, topic: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignReviewerToTopic(reviewer: Principal, topic: bigint, startDate: bigint, endDate: bigint): Promise<void>;
    clearAllProposals(): Promise<void>;
    fetchIndividualProposal(proposalId: bigint): Promise<string>;
    adminAddReview(proposalId: bigint, reviewerPrincipal: Principal, reviewLink: string, recommendation: Recommendation, comment: string): Promise<void>;
    adminRemoveReview(proposalId: bigint, reviewerPrincipal: Principal, comment: string): Promise<void>;
    fixReviewStatus(proposalId: bigint, reviewerPrincipal: Principal, comment: string): Promise<FixReviewStatusResult>;
    getAuditLog(page: bigint, pageSize: bigint): Promise<Array<AuditLogEntry>>;
    getAuditLogSize(): Promise<bigint>;
    getAllAdmins(): Promise<Array<Principal>>;
    getAllProposalIds(): Promise<Array<bigint>>;
    getAllReviewers(): Promise<Array<ReviewerWithAssignments>>;
    getAllTopics(): Promise<Array<[bigint, string]>>;
    getAuthorizedProposalSubmitter(): Promise<Principal | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getProposal(proposalId: bigint): Promise<Proposal | null>;
    getProposalReviews(proposalId: bigint): Promise<Array<Review>>;
    getProposals(topicFilter: bigint | null): Promise<Array<Proposal>>;
    getRecommendationCounts(proposalId: bigint): Promise<[bigint, bigint]>;
    getReviewer(principal: Principal): Promise<Reviewer | null>;
    getReviewerAssignments(principal: Principal): Promise<Array<[bigint, ReviewerAssignment]>>;
    getReviewerDetail(principal: Principal): Promise<ReviewerDetail | null>;
    getReviewerMissedProposals(principal: Principal): Promise<Array<Proposal>>;
    getReviewerReviewHistory(principal: Principal): Promise<Array<Review>>;
    getReviewerTodos(principal: Principal): Promise<Array<Proposal>>;
    getTopicDisplayName(topicId: bigint): Promise<string>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isAdmin(principal: Principal): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    isReviewer(): Promise<boolean>;
    removeAdmin(principal: Principal): Promise<void>;
    removeProposal(proposalId: bigint): Promise<void>;
    removeReviewer(principal: Principal): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveExternalProposal(newProposal: Proposal): Promise<boolean>;
    saveExternalProposals(newProposals: Array<Proposal>): Promise<Array<bigint>>;
    setAuthorizedProposalSubmitter(principal: Principal | null): Promise<void>;
    submitReview(proposalId: bigint, reviewLink: string, recommendation: Recommendation): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateReviewLink(proposalId: bigint, reviewerPrincipal: Principal, newLink: string, comment: string): Promise<boolean>;
    updateReviewer(principal: Principal, nickname: string, forumProfileUrl: string): Promise<AddOrUpdateResult>;
}
import type { AddOrUpdateResult as _AddOrUpdateResult, FixReviewStatusResult as _FixReviewStatusResult, Proposal as _Proposal, Recommendation as _Recommendation, Review as _Review, Reviewer as _Reviewer, ReviewerAssignment as _ReviewerAssignment, ReviewerDetail as _ReviewerDetail, ReviewerStatus as _ReviewerStatus, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addAdmin(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAdmin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAdmin(arg0);
            return result;
        }
    }
    async addOrUpdateReviewer(arg0: Principal, arg1: string, arg2: string): Promise<AddOrUpdateResult> {
        if (this.processError) {
            try {
                const result = await this.actor.addOrUpdateReviewer(arg0, arg1, arg2);
                return from_candid_AddOrUpdateResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOrUpdateReviewer(arg0, arg1, arg2);
            return from_candid_AddOrUpdateResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async addProposal(arg0: bigint, arg1: string, arg2: bigint, arg3: bigint, arg4: bigint, arg5: bigint, arg6: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addProposal(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProposal(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignReviewerToTopic(arg0: Principal, arg1: bigint, arg2: bigint, arg3: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignReviewerToTopic(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignReviewerToTopic(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async clearAllProposals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearAllProposals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearAllProposals();
            return result;
        }
    }
    async fetchIndividualProposal(arg0: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchIndividualProposal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchIndividualProposal(arg0);
            return result;
        }
    }
    async fixReviewStatus(arg0: bigint, arg1: Principal, arg2: string): Promise<FixReviewStatusResult> {
        if (this.processError) {
            try {
                const result = await this.actor.fixReviewStatus(arg0, arg1, arg2);
                return from_candid_FixReviewStatusResult_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fixReviewStatus(arg0, arg1, arg2);
            return from_candid_FixReviewStatusResult_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllAdmins(): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAdmins();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAdmins();
            return result;
        }
    }
    async getAllProposalIds(): Promise<Array<bigint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProposalIds();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProposalIds();
            return result;
        }
    }
    async getAllReviewers(): Promise<Array<ReviewerWithAssignments>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllReviewers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllReviewers();
            return result;
        }
    }
    async getAllTopics(): Promise<Array<[bigint, string]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTopics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTopics();
            return result;
        }
    }
    async getAuthorizedProposalSubmitter(): Promise<Principal | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAuthorizedProposalSubmitter();
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAuthorizedProposalSubmitter();
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProposal(arg0: bigint): Promise<Proposal | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProposal(arg0);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProposal(arg0);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProposalReviews(arg0: bigint): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProposalReviews(arg0);
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProposalReviews(arg0);
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProposals(arg0: bigint | null): Promise<Array<Proposal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProposals(to_candid_opt_n18(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProposals(to_candid_opt_n18(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getRecommendationCounts(arg0: bigint): Promise<[bigint, bigint]> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecommendationCounts(arg0);
                return [
                    result[0],
                    result[1]
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecommendationCounts(arg0);
            return [
                result[0],
                result[1]
            ];
        }
    }
    async getReviewer(arg0: Principal): Promise<Reviewer | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getReviewer(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReviewer(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReviewerAssignments(arg0: Principal): Promise<Array<[bigint, ReviewerAssignment]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReviewerAssignments(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReviewerAssignments(arg0);
            return result;
        }
    }
    async getReviewerDetail(arg0: Principal): Promise<ReviewerDetail | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getReviewerDetail(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReviewerDetail(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReviewerMissedProposals(arg0: Principal): Promise<Array<Proposal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReviewerMissedProposals(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReviewerMissedProposals(arg0);
            return result;
        }
    }
    async getReviewerReviewHistory(arg0: Principal): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReviewerReviewHistory(arg0);
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReviewerReviewHistory(arg0);
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReviewerTodos(arg0: Principal): Promise<Array<Proposal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReviewerTodos(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReviewerTodos(arg0);
            return result;
        }
    }
    async getTopicDisplayName(arg0: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getTopicDisplayName(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTopicDisplayName(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async isAdmin(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdmin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdmin(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isReviewer(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isReviewer();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isReviewer();
            return result;
        }
    }
    async removeAdmin(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeAdmin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeAdmin(arg0);
            return result;
        }
    }
    async removeProposal(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeProposal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeProposal(arg0);
            return result;
        }
    }
    async removeReviewer(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeReviewer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeReviewer(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveExternalProposal(arg0: Proposal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.saveExternalProposal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveExternalProposal(arg0);
            return result;
        }
    }
    async saveExternalProposals(arg0: Array<Proposal>): Promise<Array<bigint>> {
        if (this.processError) {
            try {
                const result = await this.actor.saveExternalProposals(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveExternalProposals(arg0);
            return result;
        }
    }
    async setAuthorizedProposalSubmitter(arg0: Principal | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setAuthorizedProposalSubmitter(to_candid_opt_n25(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAuthorizedProposalSubmitter(to_candid_opt_n25(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async submitReview(arg0: bigint, arg1: string, arg2: Recommendation): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitReview(arg0, arg1, to_candid_Recommendation_n26(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitReview(arg0, arg1, to_candid_Recommendation_n26(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateReviewLink(arg0: bigint, arg1: Principal, arg2: string, arg3: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateReviewLink(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateReviewLink(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async adminAddReview(arg0: bigint, arg1: Principal, arg2: string, arg3: Recommendation, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminAddReview(arg0, arg1, arg2, to_candid_Recommendation_n26(this._uploadFile, this._downloadFile, arg3), arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminAddReview(arg0, arg1, arg2, to_candid_Recommendation_n26(this._uploadFile, this._downloadFile, arg3), arg4);
            return result;
        }
    }
    async adminRemoveReview(arg0: bigint, arg1: Principal, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminRemoveReview(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminRemoveReview(arg0, arg1, arg2);
            return result;
        }
    }
    async getAuditLog(arg0: bigint, arg1: bigint): Promise<Array<AuditLogEntry>> {
        let raw: any[];
        if (this.processError) {
            try {
                raw = await this.actor.getAuditLog(arg0, arg1);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            raw = await this.actor.getAuditLog(arg0, arg1);
        }
        try {
            return (raw || []).map((e: any) => from_candid_AuditLogEntry(e));
        } catch (mappingErr) {
            console.error("[AuditLog] Mapping failed. Raw entries:", JSON.stringify(raw, (_, v) => typeof v === 'bigint' ? v.toString() : v));
            throw mappingErr;
        }
    }
    async getAuditLogSize(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getAuditLogSize();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAuditLogSize();
            return result;
        }
    }
    async updateReviewer(arg0: Principal, arg1: string, arg2: string): Promise<AddOrUpdateResult> {
        if (this.processError) {
            try {
                const result = await this.actor.updateReviewer(arg0, arg1, arg2);
                return from_candid_AddOrUpdateResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateReviewer(arg0, arg1, arg2);
            return from_candid_AddOrUpdateResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AddOrUpdateResult_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AddOrUpdateResult): AddOrUpdateResult {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_FixReviewStatusResult_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FixReviewStatusResult): FixReviewStatusResult {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Recommendation_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Recommendation): Recommendation {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Review_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Review): Review {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_ReviewerDetail_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReviewerDetail): ReviewerDetail {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_ReviewerStatus_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReviewerStatus): ReviewerStatus {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Proposal]): Proposal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Reviewer]): Reviewer | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ReviewerDetail]): ReviewerDetail | null {
    return value.length === 0 ? null : from_candid_ReviewerDetail_n21(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: {
        paid: null;
    } | {
        volunteer: null;
    };
    topic: bigint;
    link: string;
    timestamp: bigint;
    recommendation: _Recommendation;
    reviewer: _Reviewer;
    proposalId: bigint;
}): {
    status: Variant_paid_volunteer;
    topic: bigint;
    link: string;
    timestamp: bigint;
    recommendation: Recommendation;
    reviewer: Reviewer;
    proposalId: bigint;
} {
    return {
        status: from_candid_variant_n15(_uploadFile, _downloadFile, value.status),
        topic: value.topic,
        link: value.link,
        timestamp: value.timestamp,
        recommendation: from_candid_Recommendation_n16(_uploadFile, _downloadFile, value.recommendation),
        reviewer: value.reviewer,
        proposalId: value.proposalId
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    paidReviews: bigint;
    status: _ReviewerStatus;
    currentAssignments: Array<[bigint, _ReviewerAssignment]>;
    totalReviews: bigint;
    reviewer: _Reviewer;
    voluntaryReviews: bigint;
    allAssignments: Array<[bigint, _ReviewerAssignment]>;
}): {
    paidReviews: bigint;
    status: ReviewerStatus;
    currentAssignments: Array<[bigint, ReviewerAssignment]>;
    totalReviews: bigint;
    reviewer: Reviewer;
    voluntaryReviews: bigint;
    allAssignments: Array<[bigint, ReviewerAssignment]>;
} {
    return {
        paidReviews: value.paidReviews,
        status: from_candid_ReviewerStatus_n23(_uploadFile, _downloadFile, value.status),
        currentAssignments: value.currentAssignments,
        totalReviews: value.totalReviews,
        reviewer: value.reviewer,
        voluntaryReviews: value.voluntaryReviews,
        allAssignments: value.allAssignments
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    paid: null;
} | {
    volunteer: null;
}): Variant_paid_volunteer {
    return "paid" in value ? Variant_paid_volunteer.paid : "volunteer" in value ? Variant_paid_volunteer.volunteer : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    reject: null;
} | {
    adopt: null;
}): Recommendation {
    return "reject" in value ? Recommendation.reject : "adopt" in value ? Recommendation.adopt : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    updateError: null;
} | {
    duplicateError: null;
} | {
    success: null;
} | {
    notFoundError: null;
}): AddOrUpdateResult {
    return "updateError" in value ? AddOrUpdateResult.updateError : "duplicateError" in value ? AddOrUpdateResult.duplicateError : "success" in value ? AddOrUpdateResult.success : "notFoundError" in value ? AddOrUpdateResult.notFoundError : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    paidGrantee: null;
} | {
    volunteerFormerGrantee: null;
} | {
    volunteer: null;
}): ReviewerStatus {
    return "paidGrantee" in value ? ReviewerStatus.paidGrantee : "volunteerFormerGrantee" in value ? ReviewerStatus.volunteerFormerGrantee : "volunteer" in value ? ReviewerStatus.volunteer : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    invalidProposal: null;
} | {
    invalidReviewer: null;
} | {
    alreadyCorrect: null;
} | {
    fixedReviewStatus: null;
}): FixReviewStatusResult {
    return "invalidProposal" in value ? FixReviewStatusResult.invalidProposal : "invalidReviewer" in value ? FixReviewStatusResult.invalidReviewer : "alreadyCorrect" in value ? FixReviewStatusResult.alreadyCorrect : "fixedReviewStatus" in value ? FixReviewStatusResult.fixedReviewStatus : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Review>): Array<Review> {
    return value.map((x)=>from_candid_Review_n13(_uploadFile, _downloadFile, x));
}
function to_candid_Recommendation_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Recommendation): _Recommendation {
    return to_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Principal | null): [] | [Principal] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Recommendation): {
    reject: null;
} | {
    adopt: null;
} {
    return value == Recommendation.reject ? {
        reject: null
    } : value == Recommendation.adopt ? {
        adopt: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function from_candid_AuditActionType(value: any): AuditActionType {
    if (value == null || typeof value !== "object") return AuditActionType.addReview;
    return "addReview" in value ? AuditActionType.addReview :
           "removeReview" in value ? AuditActionType.removeReview :
           "editReviewLink" in value ? AuditActionType.editReviewLink :
           "fixReviewStatus" in value ? AuditActionType.fixReviewStatus :
           AuditActionType.addReview;
}
function from_candid_AuditLogEntry(value: any): AuditLogEntry {
    const toOpt = (v: any): string | null => {
        if (v == null) return null;
        if (Array.isArray(v)) return v.length === 0 ? null : String(v[0]);
        return String(v);
    };
    const safeActionType = (() => {
        try { return from_candid_AuditActionType(value?.actionType); } catch { return AuditActionType.addReview; }
    })();
    return {
        id: value?.id ?? BigInt(0),
        timestamp: value?.timestamp ?? BigInt(0),
        adminPrincipal: value?.adminPrincipal ?? { toString: () => "unknown", toText: () => "unknown" },
        actionType: safeActionType,
        proposalId: value?.proposalId ?? BigInt(0),
        proposalTitle: value?.proposalTitle ?? "",
        reviewerPrincipal: value?.reviewerPrincipal ?? { toString: () => "unknown", toText: () => "unknown" },
        reviewerNickname: value?.reviewerNickname ?? "",
        comment: value?.comment ?? "",
        beforeValue: toOpt(value?.beforeValue),
        afterValue: toOpt(value?.afterValue),
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
